# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:mac)


platform :mac do
  desc "Build release from CI"
  lane :release_ci do

    setup_ci()
    
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_KEY_CONTENT_BASE64"],
      is_key_content_base64: true
    )
    # Prepare certificates using Match
    match(
      type: "developer_id", 
      readonly: true,
      app_identifier: [
        "internxt.InternxtDesktop", 
        "internxt.InternxtDesktop.sync"
      ],
    )

    # Build, archive and sign the .app
    build_mac_app(
      clean: true,
      output_directory: 'build',
      export_method: "developer-id",
      scheme: "InternxtDesktop",
    )

    notarize(
      package: './build/Internxt Drive.app',
    )
     
  end
end
