# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:macos)

team_id("JR4S3SY396")


platform :macos do
  desc "Build release"
  lane :release do
    # add actions here: https://docs.fastlane.tools/actions
    build_mac_app(
      scheme: "InternxtDesktop",
      export_method: 'package',
    )
  end
end
