name: Build and Sign Internxt Desktop MacOS App

on:
  push:
    branches:
      - feature/automatic-build-ga

# This envs are available for all the steps
env:
  KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
  CODESIGN_IDENTITY: "Apple Distribution: Internxt Universal Technologies Sociedad Limitada (JR4S3SY396)"
  APPLE_DEVELOPMENT_TEAM: "JR4S3SY396"
jobs:
  build:
    runs-on: macos-13
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: Install Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/internxt_desktop_ci_profile.provisionprofile

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
            
      - name: Run Fastlane release
        run: fastlane release_ci --verbose
      # - name: Build and Sign
      #  run: |
      #    xcodebuild -project InternxtDesktop.xcodeproj -scheme InternxtDesktop -configuration Release
      
      - name: Clean Up Runner
        run: security delete-keychain $KEYCHAIN_PATH



          
