name: Build and Sign Internxt Desktop MacOS App

on:
  push:
    branches:
      - feature/automatic-build-ga

# This envs are available for all the steps
env:
  KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
  APP_STORE_KEY_ID: ${{secrets.APP_STORE_KEY_ID}}
  APP_STORE_ISSUER_ID: ${{secrets.APP_STORE_ISSUER_ID}}
  APP_STORE_KEY_CONTENT: ${{secrets.APP_STORE_KEY_CONTENT}}
  #CODESIGN_IDENTITY: "Apple Distribution: Internxt Universal Technologies Sociedad Limitada (JR4S3SY396)"
  #APPLE_DEVELOPMENT_TEAM: "JR4S3SY396"
jobs:
  build:
    runs-on: macos-13
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add env.json
        run: echo ${{ secrets.JSON_ENV }} > ./InternxtDesktop/env.local.json
      
      - name: Add App Store JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "app_store_key.json"
          json: ${{ secrets.APP_STORE_JSON }}
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install create-dmg
        run: npm install -g create-dmg
      
      
      - name: Run Fastlane release
        run: fastlane release_ci --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      
      - name: Save logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: fastlane-logs
          path: /Users/runner/Library/Logs/gym/

      - name: Download all workflow run artifacts
        if: always()
        uses: actions/download-artifact@v3



          
