name: Build and Sign Internxt Desktop MacOS App - Beta

on:
  push:
    branches:
      - feature/automatic-build-ga

# This envs are available for all the steps
env:
  KEYCHAIN_PATH: $RUNNER_TEMP/app-signing.keychain-db
  APP_STORE_KEY_ID: ${{secrets.APP_STORE_KEY_ID}}
  APP_STORE_ISSUER_ID: ${{secrets.APP_STORE_ISSUER_ID}}
  APP_STORE_KEY_CONTENT: ${{secrets.APP_STORE_KEY_CONTENT}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SLACK_WEBHOOK_MAC_TEAM: ${{secrets.SLACK_WEBHOOK_MAC_TEAM}}
jobs:
  build:
    runs-on: macos-13
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add env.json
        run: echo ${{ secrets.JSON_ENV }} > ./InternxtDesktop/env.local.json
      
      - name: Add App Store JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "app_store_key.json"
          json: ${{ secrets.APP_STORE_JSON }}
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install create-dmg
        run: npm install -g create-dmg
      
      
      - name: Run Fastlane release
        run: fastlane beta_ci --verbose
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}

      - name: Upload DMG to workflow
        uses: actions/upload-artifact@v3
        with:
          name: Internxt Drive
          path: ./build/**/*.dmg
      
      - name: Download DMG artifact
        uses: actions/download-artifact@v3
        with:
          name: Internxt 2.1.0.dmg
          path: ./build
       


          
