name: Build and Sign Internxt Desktop MacOS App - Prod
on:
  workflow_dispatch:

# This envs are available for all the steps
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SLACK_WEBHOOK_MAC_TEAM: ${{secrets.SLACK_WEBHOOK_MAC_TEAM}}

jobs:
  build:
    runs-on: macos-15  # Cambiado a macos-15 que tiene Xcode 16
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Select Xcode version explicitly
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app
      
      - name: Show Xcode and Swift versions
        run: |
          xcodebuild -version
          swift --version
          xcode-select -p
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Add env.json
        id: create-env-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env.local.json"
          json: ${{ secrets.JSON_ENV }}
          dir: 'InternxtDesktop/'
      
      - name: Add App Store JSON
        id: create-app-store-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "app_store_key.json"
          json: ${{ secrets.APP_STORE_JSON }}
      
      # See https://github.com/actions/runner/issues/2958
      - name: Install Python Setuptools
        run: sudo -H pip install setuptools
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install create-dmg
        run: npm install -g create-dmg
      
      - name: Run Fastlane release
        run: fastlane prod_ci --verbose 2>&1 | tee build.log
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      
      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: |
            build.log
            build/logs/
            ~/Library/Logs/gym/
